services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    mem_limit: "1024m"
    mem_reservation: "512m"
    cpus: 2
    healthcheck:
      test: curl -Is localhost:8080/actuator/health | head -n 1 | grep 200 || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
